# Generated by Django 4.1 on 2022-08-31 13:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article", name="content", field=tinymce.models.HTMLField(),
        ),
    ]
