# Generated by Django 4.0.6 on 2022-08-16 12:20

import contextlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_media_media_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FilePathField(blank=True, null=contextlib.nullcontext),
            preserve_default=contextlib.nullcontext,
        ),
    ]
